Feature/coinmate
jjxtra/ExchangeSharp pull request #718
Opened 2022-01-24 21:43 UTC by bezysoftware

Resolves #642

2022-01-24 22:06 UTC, vslee requested changes
Could you add a row for this exchange to the table in README.md?

2022-01-24 23:11 UTC, vslee requested changes

2022-01-24 23:11 UTC, vslee commented on src/ExchangeSharp/API/Exchanges/Coinmate/ExchangeCoinmateAPI.cs
> +	}
Could you add a partial class to the end like the other exchanges, such as:
https://github.com/jjxtra/ExchangeSharp/blob/6e327ab82aff0db6cdc0846bbdc651324e525e8b/src/ExchangeSharp/API/Exchanges/Coinbase/ExchangeCoinbaseAPI.cs#L818

2022-01-25 08:12 UTC, bezysoftware commented
> Could you add a row for this exchange to the table in README.md?

Done

2022-01-25 08:52 UTC, vslee approved these changes

2022-01-25 08:52 UTC, merged